# version: '3.8'
services:
  postgres-guitarra:
    image: postgres:17-alpine
    container_name: postgres-guitarra
    restart: always
    environment:
      POSTGRES_USER: joao
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: guitarra
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: